[package]
name = "ai-rustdoc"
version = "0.0.0"
edition = "2021"

[dependencies]
# Easily run child processes, redirect IO, and capture their output.
duct = "0.13"
# Serialization / deserialization framework
serde = { version = "1", features = ["derive"] }
serde_json = "1"
